#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "http://github.com/dib-lab/2017-07-05-UCSC"
workshop_site   : "http://dib-lab.github.io/2017-07-05-UCSC"
#--------------------------------------------------------------------------------
# Standard Data Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
dc_blog        : "http://ivory.idyll.org/lab"
dc_contact     : "lcirberjr@ucdavis.edu"
dc_github      : "http://github.com/dib-lab"
swc_installer   : "http://files.software-carpentry.org/SWCarpentryInstaller.exe"
swc_lessons     : "http://software-carpentry.org/v5/novice"
dc_site        : "https://datacarpentry.org"
dc_twitter     : "http://twitter.com/luizirber"
#swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
#dc_pre_survey   : "https://www.surveymonkey.com/r/dc_pre_workshop_v1"
#dc_post_survey  : "https://www.surveymonkey.com/r/dc_post_workshop_v1"
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
